var categoryList = {
    'Alexa Skills': 'alexa-skills',
    'All Departments': 'aps',
    'Amazon Devices': 'amazon-devices',
    'Amazon Explore': 'live-explorations',
    'Amazon Fresh': 'amazonfresh',
    'Amazon Pantry': 'pantry',
    'Amazon Warehouse': 'warehouse-deals',
    'Appliances': 'appliances',
    'Apps & Games': 'mobile-apps',
    'Arts, Crafts & Sewing': 'arts-crafts',
    'Audible Books & Originals': 'audible',
    'Automotive Parts & Accessories': 'automotive',
    'Baby': 'baby-products',
    'Beauty & Personal Care': 'beauty',
    'Books': 'stripbooks',
    'CDs & Vinyl': 'popular',
    'Cell Phones & Accessories': 'mobile',
    'Clothing, Shoes & Jewelry': 'fashion',
    'Collectibles & Fine Art': 'collectibles',
    'Computers': 'computers',
    'Courses': 'courses',
    'Credit and Payment Cards': 'financial',
    'Digital Educational Resources': 'edu-alt-content',
    'Digital Music': 'digital-music',
    'Electronics': 'electronics',
    'Garden & Outdoor': 'lawngarden',
    'Gift Cards': 'gift-cards',
    'Grocery & Gourmet Food': 'grocery',
    'Handmade': 'handmade',
    'Health, Household & Baby Care': 'hpc',
    'Home & Business Services': 'local-services',
    'Home & Kitchen': 'garden',
    'Industrial & Scientific': 'industrial',
    'Just for Prime': 'prime-exclusive',
    'Kindle Store': 'digital-text',
    'Luggage & Travel Gear': 'fashion-luggage',
    'Magazine Subscriptions': 'magazines',
    'Movies & TV': 'movies-tv',
    'Musical Instruments': 'mi',
    'Office Products': 'office-products',
    'Pet Supplies': 'pets',
    'Premium Beauty': 'luxury-beauty',
    'Prime Video': 'instant-video',
    'Smart Home': 'smart-home',
    'Software': 'software',
    'Sports & Outdoors': 'sporting',
    'Subscription Boxes': 'subscribe-with-amazon',
    'Tools & Home Improvement': 'tools',
    'Toys & Games': 'toys-and-games',
    'Under $10': 'under-ten-dollars',
    'Vehicles': 'vehicles',
    'Video Games': 'videogames',
    'Whole Foods Market': 'wholefoods',
    'Baby': 'fashion-baby',
    'Boys': 'fashion-boys',
    'Girls': 'fashion-girls',
    'Men': 'fashion-mens',
    'Women': 'fashion-womens'
}
